In [1]:
import requests
import shutil

In [2]:
api_key = "AIzaSyC7CEkAND6bNxkwUi4POEHg4XAZ90TsTpU"
size = "200x200"
zoom = 14
center = ""
feature = "all"
element = "all"
visibility = "off"
color = "0xffffff"
feature_road = "road.arterial"
element_road = "geometry"
visibility_road = "simplified"
color_road = "0x000000"

In [3]:
static_url = "https://maps.googleapis.com/maps/api/staticmap?"
style = "feature:" + feature + "|element:" + element + "|visibility:" + visibility + "|color:" + color
style_road = "feature:" + feature_road + "|element:" + element_road + "|visibility:" + visibility_road + "|color:" + color_road
url = static_url + "center=" + center + "&zoom=" + str(zoom) + "&size=" + size + "&key=" + api_key
print(style)
print(style_road)
print(url)

feature:all|element:all|visibility:off|color:0xffffff
feature:road.arterial|element:geometry|visibility:simplified|color:0x000000
https://maps.googleapis.com/maps/api/staticmap?center=&zoom=14&size=200x200&key=AIzaSyC7CEkAND6bNxkwUi4POEHg4XAZ90TsTpU


In [4]:
r = requests.get(static_url + "center=" + center + "&zoom=" + str(zoom) + "&size=" + size + "&style=" + style + "&style=" + style_road +"&key=" + api_key)

In [5]:
print(r.content)

b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\xc8\x00\x00\x00\xc8\x08\x03\x00\x00\x00\x9a\x86^\xac\x00\x00\x02\xf1PLTE\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x03\x03\x05\x05\x05\x08\x08\x08\n\n\n\r\r\r\r\r\r\x10\x10\x10\x13\x13\x13\x15\x15\x15\x18\x18\x18\x1b\x1b

In [6]:
print(r)

<Response [200]>


In [7]:
if r.status_code == 200:
    with open("img.png", 'wb') as f:
        f.write(r.content)

In [8]:
from PIL import Image
import numpy as np
image = Image.open('img.png')
# print(image.mode)
# # show the image
# # image.show()

In [9]:
# red, green, blue = image.split()
# # red.show()

In [10]:
x = 0
y = 0
width = 180
height = 180
temp = image.crop((x,y, x + width ,y + height))
print(temp.size)
temp.show()

(180, 180)


In [11]:
arr = np.array(temp)
print(arr)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
text_image = ""
for i in range(len(arr)):
    temp = ""
    for j in range(len(arr[i])):
        if arr[i][j] >= 50 :
            temp += "_"
        else:
            temp += "#"
    temp += '\n'
    text_image += temp
    
    
newLoc = "./resource/generated_maps/test" + "google" + ".txt"
text_file = open(newLoc , "w")
text_file.write(text_image)
text_file.close()

In [13]:
from countryinfo import CountryInfo
countries = CountryInfo()

In [14]:
for c in countries.all():
    try:
        print(CountryInfo(c).capital())
    except:
        pass

Skopje
Paris
Tehran
Yaren
King Edward Point
Djibouti
Monrovia
Lusaka
Islamabad
Papeetē
Dakar
Doha
Washington D.C.
Bandar Seri Begawan
Fakaofo
Kiev
Kampala
Copenhagen
Honiara
Tripoli
Asmara
Prague
Lilongwe
Palikir
Tashkent
Zagreb
Port Louis
Canberra
Riyadh
Kigali

Avarua
Lomé
Brussels
City of Victoria
San Salvador
Castries
Buenos Aires
Kuwait City
Port-aux-Français
Luanda
Bangkok
Bissau
Sucre
Yerevan
Tbilisi
Hanoi
Montevideo
Thimphu
Jamestown
Ouagadougou
London
Longyearbyen
Nicosia
Reykjavik
Yaoundé
Niamey
Sofia
Brasília
Suva
Tokyo

Majuro
Cayenne
Saint Helier
Ashgabat
Nouakchott
Hamilton
Kinshasa
Ljubljana
El Aaiún
Stockholm
Bucharest
Monaco
Douglas
Pago Pago
Dushanbe
Minsk
Colombo
Baghdad
Abuja
Seoul
Abu Dhabi
Tórshavn
Kathmandu
Lima
Athens
Quito
Taipei
Addis Ababa
Bridgetown
Sarajevo
Freetown
West Island
Hagåtña
Vientiane
Manila
Manama
Nuku'alofa
New Delhi
Mogadishu
Juba
Jerusalem
Phnom Penh
San Juan
Harare
Malabo
Banjul
Helsinki
City of San Marino
Accra
Khartoum
Vienna
Nairobi
Kabul

In [1]:
# import pycountry as countries
from countryinfo import CountryInfo
from PIL import Image
import numpy as np
import requests
import shutil
countries = CountryInfo()

x = 0
y = 0
width = 100
height = 90

basewidth = 28
hsize = 26

api_key = "AIzaSyC7CEkAND6bNxkwUi4POEHg4XAZ90TsTpU"
size = "100x100"
zoom = 14
scale = 2
feature = "all"
element = "all"
visibility = "off"
color = "0xffffff"
feature_road = "road"
element_road = "geometry"
visibility_road = "simplified"
color_road = "0x000000"
weight_road = "2"
static_url = "https://maps.googleapis.com/maps/api/staticmap?"
style = "feature:" + feature + "|element:" + element + "|visibility:" + visibility + "|color:" + color
style_road = "feature:" + feature_road + "|element:" + element_road + "|visibility:" + visibility_road + "|color:" + color_road + "|weight:" + weight_road

for country in countries.all():
    try :
        name = CountryInfo(country).capital()
    except:
        continue
        
    r = requests.get(static_url + "center=" + str(name) + "&zoom=" + str(zoom) + "&size=" + size + "&scale=" + str(scale) + "&style=" + style + "&style=" + style_road +"&key=" + api_key)
    if r.status_code == 200:
        with open("./resource/generated_images/img_" + str(name) + ".png", 'wb') as f:
            f.write(r.content)
            
    image = Image.open('./resource/generated_images/img_' + str(name) + '.png')
    temp = image.crop((x,y, x + width ,y + height))
    temp = temp.resize((basewidth,hsize), Image.LANCZOS)
    temp.save('./resource/generated_images/img_' + str(name) + '.png')
#     temp.show()
    arr = np.array(temp)
    counts = 0
    text_image = ""
    for i in range(len(arr)):
        temp = ""
        for j in range(len(arr[i])):
            if arr[i][j] >= 50 :
                temp += "_"
                counts += 1
            else:
                temp += "#"
        temp += '\n'
        text_image += temp
    if counts / (basewidth * hsize) >= 0.25 and counts / (basewidth * hsize) <= 0.50:   
        newLoc = "./resource/generated_maps/test" + str(name) + ".txt"
        text_file = open(newLoc , "w")
        text_file.write(text_image)
        text_file.close()
        print("Completed : ", name)

Completed :  Skopje
Completed :  Paris
Completed :  Tehran
Completed :  Monrovia
Completed :  Doha
Completed :  Washington D.C.
Completed :  Kampala
Completed :  Copenhagen
Completed :  Tripoli
Completed :  Asmara
Completed :  Prague
Completed :  Tashkent
Completed :  Canberra
Completed :  Riyadh
Completed :  Kigali
Completed :  Lomé
Completed :  Brussels
Completed :  San Salvador
Completed :  Castries
Completed :  Buenos Aires
Completed :  Kuwait City
Completed :  Luanda
Completed :  Bangkok
Completed :  Bissau
Completed :  Sucre
Completed :  Yerevan
Completed :  Hanoi
Completed :  Montevideo
Completed :  Thimphu
Completed :  London
Completed :  Nicosia
Completed :  Niamey
Completed :  Sofia
Completed :  Brasília
Completed :  Cayenne
Completed :  Ashgabat
Completed :  El Aaiún
Completed :  Stockholm
Completed :  Bucharest
Completed :  Monaco
Completed :  Dushanbe
Completed :  Minsk
Completed :  Colombo
Completed :  Abuja
Completed :  Seoul
Completed :  Abu Dhabi
Completed :  Tórshavn
